### ISSUE TITLE
UnifiVPNRestart

### ISSUE THREAD

**Issue by CW-Khristos** [rambopfc/UnifiVPNRestart#1]
Hey @rambopfc 

It's CJ
reaching out to actually inquire about how to go about setting up this on a new unifi instance
drop me a line; 

*Edited to remove sensitive info

**Comment by rambopfc** [comment]
Hey CJ! Very sorry, i don't normally check this email address at all.

I'm in NJ at the moment so away from my PC but i vaguely remember how this
works lol.
The .JSON file is on the unifi controller, it should be edited to include
the task in the .JSON file on this GitHub repo. That config tells each
device that provisions to download and run the runonprovisoion.sh. this has
to be done for it to download the restart script, and create the log file
and task. The task can't be created before the VPN restart script exists on
the device, so the run on provision script is the work around for that.
Obviously you should edit it to point to your own copies of the script in
your own repo, just in case!

I'll be back Wednesday and check with you if you ran into any issues. Hope
you're doing well!

**Comment by CW-Khristos** [comment]
Quite alright on the delay
I'm doing well enough; working again, trying to get things caught up
Once I found out you weren't at CW any more I figured this would probably be the only way to get in touch

obviously editing the config and sh scripts is no problem; just more so getting the files where they need to go to implement
Do you happen to remember the file paths or still have a copy of a setup SOP?
Only asking cause I am still fairly new to managing these Unifi devices remotely; and I'm going to need to train our other employees and the bossman on how to implement this for our Unifi devices.

**Comment by rambopfc** [comment]
The config file is really the only thing that needs to go anywhere. After looking at [this article](https://help.ui.com/hc/en-us/articles/215458888-UniFi-USG-Advanced-Configuration-Using-config-gateway-json) again, I remember that it doesn't exist by default. The location for us was /usr/lib/unifi/data/sites/[site name/default]/ because our controller was hosted on a ubuntu instance. The log file will get created in /var/log/ and the scripts themselves get downloaded into /config/scripts/ on the device itself. The script files just need to be on a web server somewhere that the config and provision script can download from.
